export MODULES:=ModemApp ate system

ifeq ($(strip $(KING_SDK_TTS_SUPPORT)),TRUE)
MODULES += tts
COMMON_GLOBAL_CFLAGS += -DKING_SDK_TTS_SUPPORT
endif

ifeq ($(strip $(KING_SDK_FTM_SUPPORT)),TRUE)
MODULES += ftm
endif

ifeq ($(strip $(KING_SDK_DTLS_SUPPORT)),TRUE)
MODULES += dtls
COMMON_GLOBAL_CFLAGS += -DKING_SDK_DTLS_SUPPORT
endif

ifeq ($(strip $(KING_SDK_LWM2M_SUPPORT)),TRUE)
MODULES += lwm2m
COMMON_GLOBAL_CFLAGS += -DKING_SDK_LWM2M_SUPPORT
endif

ifeq ($(strip $(KING_SDK_MBEDTLS_SUPPORT)),TRUE)
MODULES += mbedtls
COMMON_GLOBAL_CFLAGS += -DKING_SDK_MBEDTLS_SUPPORT
endif

ifeq ($(strip $(KING_SDK_MQTT_SUPPORT)),TRUE)
MODULES += mqtt
COMMON_GLOBAL_CFLAGS += -DKING_SDK_MQTT_SUPPORT
endif

ifeq ($(strip $(KING_SDK_HTTP_SUPPORT)),TRUE)
MODULES += http
COMMON_GLOBAL_CFLAGS += -DKING_SDK_HTTP_SUPPORT
endif

ifeq ($(strip $(KING_SDK_AEP_SUPPORT)),TRUE)
MODULES += aep
COMMON_GLOBAL_CFLAGS += -DKING_SDK_AEP_SUPPORT
endif