/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/
#include "at_sa.h"
#include "at_utils.h"
#include "at_define.h"
#include "crc32.h"

#define FSM_POWER_DOWN_CMD_ENABLE   0x00000001
#define FSM_NORMAL_CMD_ENABLE       0x00000002
#define FSM_CHGR_NORMAL_CMD_ENABLE  0x00000004
#define FSM_CHGR_ONLY_CMD_ENABLE    0x00000008
#define FSM_ALARM_NORMAL_CMD_ENABLE 0x00000010
#define FSM_ALARM_ONLY_CMD_ENABLE   0x00000020
#define FSM_SLEEP_CMD_ENABLE        0x00000040
#define FSM_CFW_OFF_CMD_ENABLE      0x00000080

#define FSM_FULL_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                    |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                    |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                    |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_LIMITED1_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)     \
                                        |(FSM_ALARM_ONLY_CMD_ENABLE))

#define FSM_LIMITED2_STATUS_CMD_ENABLE  ((FSM_NORMAL_CMD_ENABLE)        \
                                        |(FSM_CHGR_NORMAL_CMD_ENABLE)|(FSM_CHGR_ONLY_CMD_ENABLE)        \
                                        |(FSM_ALARM_NORMAL_CMD_ENABLE)|(FSM_ALARM_ONLY_CMD_ENABLE)      \
                                        |(FSM_SLEEP_CMD_ENABLE)|(FSM_CFW_OFF_CMD_ENABLE))

#define FSM_DISABLE_STATUS_CMD_ENABLE   (0x00000000)

#define AT_PROC_MODE_CMD_ENABLE 0x00000001
#define AT_PROC_MODE_OLCMD_ENABLE   0x00000002
#define AT_PROC_MODE_CS_ENABLE  0x00000004
#define AT_PROC_MODE_PS_ENABLE  0x00000008

// [[Hameina[mod] 2008-4-21: can't input at, <cr>in online command state
#define AT_AT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_FA_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CR_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// ]]Hameina[mod] 2008-4-21: can't input at, <cr>in online command state

#define AT_REPEAT_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_ATD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATH_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// [[changyg[mod] 2008-4-29 :CS MODE ENABLE
#define AT_ATA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTS_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHUP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTD_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CHLD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DLST_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VTSEX_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMGS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SMGO_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMGR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSDH_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNMA_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCB_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMSS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CACM_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CSAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRES_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_COPS_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSQ_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ECSQ_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COPN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CREG_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CPOL_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// frank add start
#ifdef AT_USER_DBS
#define AT_POSI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGSN_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
// frank add start

#define AT_CCWA_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCFC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLIR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_COLR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CUSD_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CACM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CAOC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPUC_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSVM_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// add by lijingyu
#define AT_CMUX_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CFGINIT_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CFGGET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_BTSET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_WIFISET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_CPBS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_WPCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CNUM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_STGI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STA_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STNR_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMM_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CGMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_GMI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#ifndef AT_USER_DBS
#define AT_CGSN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#endif
#define AT_GSN_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATI_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIMI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SIM_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPIN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPIN2_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPINC_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLCK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPWD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRSM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAMM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SIMIF_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SVRADDR_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DATACLASS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CONNECT_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CMER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CEER_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMEE_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CFUN_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CSCS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCLK_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATE_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATV_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATQ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATZ_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALA_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CALD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ANDF_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ATX_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// #define AT_CALD_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_ANDW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S0_PERM      {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S5_PERM      {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S3_PERM      {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_S4_PERM      {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CDTMF_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IPR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_ICF_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_IFC_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_MONI_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCED_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONIEND_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONP_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_MONPEND_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCID_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CCID_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_SBBI_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBR_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_NBBW_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DPBK_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DREG_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DFFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_DSMS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_PRDU_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUST_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_AUEND_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SAIC_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBC_PERM     {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCE_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CBCM_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SCTM_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CPAS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CIND_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CLVL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CMUT_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGR_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_VGT_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CRMP_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_CAUDIO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SNFS_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_SLCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
#define AT_STCD_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

// ADD by wulc
#define AT_CRSL_PERM    {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}
// CPOF == SMSO  JYK 08/04/08
#define AT_CPOF_PERM    {FSM_LIMITED1_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_CGDCONT_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGDSCONT_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGTFT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQREQ_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGQMIN_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGATT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGACT_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGPADDR_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGDATA_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGAUTO_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGANS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCLASS_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGEREP_PERM  {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGREG_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGSMS_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CRC_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_CGCID_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_TCPIP_PERM   {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

// #define AT_ATO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_OLCMD_ENABLE}
/*BUG /wulc/2012.02.15/because AT_PROC_MODE_OLCMD_ENABLE cause cmdline parser error*/
#define AT_ATO_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_3PLUS_PERM   {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_OLCMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_MIC_PERM     {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_SPEAKER_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_RECEIVER_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}
#define AT_HEADSET_PERM {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_ADGF_PERM    {FSM_NORMAL_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE}

#define AT_NWINFO_PERM  {FSM_LIMITED2_STATUS_CMD_ENABLE,AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}

#define AT_ENG_PERM     {FSM_LIMITED2_STATUS_CMD_ENABLE, AT_PROC_MODE_CMD_ENABLE|AT_PROC_MODE_CS_ENABLE}


extern void SA_DefaultCmdHandler_AT(AT_CMD_PARA *);
extern void AT_CmdFunc_E(AT_CMD_PARA *);
extern void AT_CmdFunc_GMR(AT_CMD_PARA *);
extern void AT_CmdFunc_GMR(AT_CMD_PARA *);
extern void AT_CmdFunc_CZESVER(AT_CMD_PARA *);
extern void AT_CmdFunc_CGSN(AT_CMD_PARA *);
extern void AT_CmdFunc_AndW(AT_CMD_PARA *);
extern void AT_CmdFunc_IPR(AT_CMD_PARA *);
extern void AT_CmdFunc_CFUN(AT_CMD_PARA *);
extern void AT_CmdFunc_CCLK(AT_CMD_PARA *);
extern void AT_CmdFunc_WSOP(AT_CMD_PARA *);
extern void AT_CmdFunc_CZCHIPID(AT_CMD_PARA *);
extern void AT_CmdFunc_CZEDUMPEN(AT_CMD_PARA *);
extern void AT_CmdFunc_QPOWD(AT_CMD_PARA *);
extern void AT_CmdFunc_QSCLK(AT_CMD_PARA *);
extern void AT_CmdFunc_QTTS(AT_CMD_PARA *);
extern void AT_CmdFunc_QTTSETUP(AT_CMD_PARA *);
extern void AT_CmdFunc_CLVL(AT_CMD_PARA *);
extern void AT_CmdFunc_CZAudPlay(AT_CMD_PARA *);
extern void AT_CmdFunc_CZFPCM(AT_CMD_PARA *);
extern void AT_CmdFunc_CZGetPcmVer(AT_CMD_PARA *);
extern void AT_CmdFunc_CIMI(AT_CMD_PARA *);
extern void AT_CmdFunc_CCID(AT_CMD_PARA *);
extern void AT_CmdFunc_CPIN(AT_CMD_PARA *);
extern void AT_CmdFunc_SIMCROSS(AT_CMD_PARA *);
extern void AT_CmdFunc_SIMHOTPLUGCFG(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_QSIMDET(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_QSIMSTAT(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_QNWINFO(AT_CMD_PARA *);
extern void AT_CmdFunc_QENG(AT_CMD_PARA *);
extern void AT_CmdFunc_COPS(AT_CMD_PARA *);
extern void AT_CmdFunc_CREG(AT_CMD_PARA *);
extern void AT_CmdFunc_CEREG(AT_CMD_PARA *);
extern void AT_CmdFunc_CESQ(AT_CMD_PARA *);
extern void AT_CmdFunc_CGATT(AT_CMD_PARA *);
extern void SA_DefaultCmdHandler_CMUX(AT_CMD_PARA *);
extern void AT_CmdFunc_CPMS(AT_CMD_PARA *);
extern void AT_CmdFunc_CNMI(AT_CMD_PARA *);
extern void AT_CmdFunc_CMGR(AT_CMD_PARA *);
extern void AT_CmdFunc_CMGS(AT_CMD_PARA *);
extern void AT_CmdFunc_CMGD(AT_CMD_PARA *);
extern void AT_CmdFunc_QICSGP(AT_CMD_PARA *);
extern void AT_CmdFunc_QIACT(AT_CMD_PARA *);
extern void AT_CmdFunc_QIDEACT(AT_CMD_PARA *);
extern void AT_CmdFunc_QIOPEN(AT_CMD_PARA *);
extern void AT_CmdFunc_QICLOSE(AT_CMD_PARA *);
extern void AT_CmdFunc_QISEND(AT_CMD_PARA *);
extern void AT_CmdFunc_QISENDEX(AT_CMD_PARA *);
extern void AT_CmdFunc_QIRD(AT_CMD_PARA *);
extern void AT_CmdFunc_QISTATE(AT_CMD_PARA *);
extern void AT_CmdFunc_QIDNSGIP(AT_CMD_PARA *);
extern void atCmdHandleD(AT_CMD_PARA *);
extern void atCmdHandleA(AT_CMD_PARA *);
extern void atCmdHandleH(AT_CMD_PARA *);
extern void atCmdHandleS0(AT_CMD_PARA *);
extern void AT_CmdFunc_Czcrmode(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_CzpEnter(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpImei(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpCsn(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpMeid(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpIpr(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpAutoOn(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpCode(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpWmac(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpNvback(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpAudTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpChgTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpLdoTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpSdTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpUartTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpKeyTest(AT_CMD_PARA *);
extern void AT_CmdFunc_CzpGpioTest(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTMODE(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTOPEN(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTAUTH(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTPARA(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTCONN(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTDISCONN(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTSUB(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTUNSUB(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTPUB(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTSTATE(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTRCVPUB(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTRCVCFG(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTPUBIN(AT_CMD_PARA *);
extern void AT_CmdFunc_IMQTTRCVPUBIN(AT_CMD_PARA *);
extern void AT_CmdFunc_QHTTPCFG(AT_CMD_PARA *);
extern void AT_CmdFunc_QHTTPURL(AT_CMD_PARA *);
extern void AT_CmdFunc_QHTTPGET(AT_CMD_PARA *);
extern void AT_CmdFunc_QHTTPREAD(AT_CMD_PARA *);
extern void AT_CmdFunc_CWLSCAN(AT_CMD_PARA *);
extern void AT_CmdFunc_CZUPCHK(AT_CMD_PARA *);
extern void AT_CmdFunc_CZUPDL(AT_CMD_PARA *);
extern void AT_CmdFunc_CZUPDATE(AT_CMD_PARA *);
extern void AT_CmdFunc_QURCCFG(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTENABLE(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTNAME(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTMAC(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTIBEACON(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTADVCFG(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTADVEN(AT_CMD_PARA *);
extern void AT_CmdFunc_CBTBCONCFG(AT_CMD_PARA *);
extern void AT_CmdFunc_CBLESEND(AT_CMD_PARA *);
extern void AT_CmdFunc_CBLEDISCONN(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_CBLESCAN(AT_CMD_PARA *);
extern void AT_CmdFunc_CBLECONN(AT_CMD_PARA *);
extern void AT_CmdFunc_CBLEUUID(AT_CMD_PARA *);
extern void AT_CmdFunc_CBLEMTU(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_CBTADVDATA(AT_CMD_PARA *pParam);

extern void AT_CmdFunc_QGPS(AT_CMD_PARA *);
extern void AT_CmdFunc_QGPSEND(AT_CMD_PARA *);
extern void AT_CmdFunc_QGPSLOC(AT_CMD_PARA *);
extern void AT_CmdFunc_CZSCANCODE(AT_CMD_PARA *);
extern void AT_CmdFunc_CZCAMPARAM(AT_CMD_PARA *);
extern VOID AT_CmdFunc_DSS(AT_CMD_PARA *pParam);
extern VOID AT_CmdFunc_SIMSWITCH(AT_CMD_PARA *pParam);
extern VOID AT_CmdFunc_CZLCDONOFF(AT_CMD_PARA *pParam);
extern VOID AT_CmdFunc_CZLCDBRIGHTNESS(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_CZLDO(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_QADC(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_CZEM2SD(AT_CMD_PARA *pParam);
extern void AT_CmdFunc_SET7SRESET(AT_CMD_PARA *pParam);

static const struct SA_COMMAND_TABLE_T g_AtCommandTable[] =
{
    {"AT", 0xC4BDF956, SA_DefaultCmdHandler_AT, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {"E", 0xD4B45A92, AT_CmdFunc_E, SA_CMDCLS_GC, AT_MODE_ENABLE_ALL, AT_ATE_PERM},
    {"+CGMR", 0x4CF5840E, AT_CmdFunc_GMR, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_CGMR_PERM},
    {"+GMR", 0xE3106DF6, AT_CmdFunc_GMR, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_GMR_PERM},
    {"+CZESVER", 0x30394BF3, AT_CmdFunc_CZESVER, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_GMR_PERM},
    {"+CGSN", 0x8CB5E79E, AT_CmdFunc_CGSN, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_CGSN_PERM},
    {"&W", 0x7708558C, AT_CmdFunc_AndW, SA_CMDCLS_GC, 1, AT_ANDW_PERM},
    {"+IPR", 0x16E22CE0, AT_CmdFunc_IPR, SA_CMDCLS_GC, AT_MODE_ENABLE_ALL, AT_IPR_PERM},
    {"+CFUN", 0xDB2D2A2F, AT_CmdFunc_CFUN, SA_CMDCLS_GC, 1, AT_AT_PERM},
    {"+CCLK", 0x368CB553, AT_CmdFunc_CCLK, SA_CMDCLS_GC, 1, AT_CCLK_PERM},
    {"+WSOP", 0x54994CC4, AT_CmdFunc_WSOP, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_CGMR_PERM},
    {"+CZCHIPID", 0xFDFF58AF, AT_CmdFunc_CZCHIPID, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_CGMR_PERM},
    {"+CZEDUMPEN", 0x1C6F6B05, AT_CmdFunc_CZEDUMPEN, SA_CMDCLS_GC, AT_MODE_ENABLE_ALL, AT_AT_PERM},
    
    {"+QPOWD", 0xED5A3968, AT_CmdFunc_QPOWD, SA_CMDCLS_GC, 1, AT_CPOF_PERM},
    {"+QSCLK", 0xCF7CB9E9, AT_CmdFunc_QSCLK, SA_CMDCLS_GC, 1, AT_AT_PERM},
    {"+QADC", 0x091AFC13, AT_CmdFunc_QADC, SA_CMDCLS_GC, 1, AT_AT_PERM},
    {"+CZLDO", 0x6CBC3BAD, AT_CmdFunc_CZLDO, SA_CMDCLS_GC, 1, AT_AT_PERM},
#ifdef KING_SDK_TTS_SUPPORT
    {"+QTTS", 0x44829FBD, AT_CmdFunc_QTTS, SA_CMDCLS_EX, 1, AT_CAUDIO_PERM},
    {"+QTTSETUP", 0x2BCF1F50, AT_CmdFunc_QTTSETUP, SA_CMDCLS_EX, 1, AT_CAUDIO_PERM},
#endif
    {"+CLVL", 0x13999D16, AT_CmdFunc_CLVL, SA_CMDCLS_EX, 1, AT_CLVL_PERM},
    {"+CZAUDPLAY", 0x2DDAB58F, AT_CmdFunc_CZAudPlay, SA_CMDCLS_EX, 1, AT_CAUDIO_PERM},
    {"+CZFPCM", 0xAA43150A, AT_CmdFunc_CZFPCM, SA_CMDCLS_EX, 1, AT_CAUDIO_PERM},
    {"+CZGETPCMVER", 0xE507CC01, AT_CmdFunc_CZGetPcmVer, SA_CMDCLS_EX, 1, AT_CAUDIO_PERM},

    {"+CIMI", 0xCC0E60E8, AT_CmdFunc_CIMI, SA_CMDCLS_ID, AT_MODE_ENABLE_ALL, AT_CIMI_PERM},
    {"+CCID", 0xDB445C87, AT_CmdFunc_CCID, SA_CMDCLS_SIM, 1, AT_CCID_PERM},
    {"+CPIN", 0x25F1A8B0, AT_CmdFunc_CPIN, SA_CMDCLS_SIM, 1, AT_CPIN_PERM},
    {"+SIMCROSS", 0x3934F479, AT_CmdFunc_SIMCROSS, SA_CMDCLS_SIM, AT_MODE_ENABLE_ALL, AT_SIM_PERM},
    {"+SIMHOTPLUGCFG", 0x9BA3C2CC, AT_CmdFunc_SIMHOTPLUGCFG, SA_CMDCLS_SIM, AT_MODE_ENABLE_ALL, AT_SIM_PERM},
    
    {"+QSIMDET", 0x6480885A, AT_CmdFunc_QSIMDET, SA_CMDCLS_SIM, AT_MODE_ENABLE_ALL, AT_SIM_PERM},
    {"+QSIMSTAT", 0xD2410277, AT_CmdFunc_QSIMSTAT, SA_CMDCLS_SIM, AT_MODE_ENABLE_ALL, AT_SIM_PERM},

    {"+QNWINFO", 0x27A53852, AT_CmdFunc_QNWINFO,  SA_CMDCLS_NW, 1, AT_NWINFO_PERM},
    {"+QENG", 0xF391785C, AT_CmdFunc_QENG, SA_CMDCLS_NW, 1, AT_NWINFO_PERM},
    {"+COPS", 0xCA8D893C, AT_CmdFunc_COPS, SA_CMDCLS_NW, 1, AT_COPS_PERM},
    {"+CREG", 0xF31C8B76, AT_CmdFunc_CREG, SA_CMDCLS_NW, 1, AT_CREG_PERM},
    {"+CEREG", 0x65BE4B6D, AT_CmdFunc_CEREG, SA_CMDCLS_NW, 1, AT_CREG_PERM},
    {"+CESQ", 0x02393E05, AT_CmdFunc_CESQ, SA_CMDCLS_NW, 1, AT_CSQ_PERM},
    {"+CGATT", 0x06B0FC01, AT_CmdFunc_CGATT, SA_CMDCLS_NW, 1, AT_CGATT_PERM},
    
    {"+CMUX", 0x23AC709F, SA_DefaultCmdHandler_CMUX, SA_CMDCLS_SS, 1, AT_CMUX_PERM},
    
    // 3GPP TS 27.005 V3.2.0
    // For SMS Commands
    //
    {"+CPMS", 0x229B016D, AT_CmdFunc_CPMS, SA_CMDCLS_SMS, 1, AT_CPMS_PERM},
    {"+CNMI", 0xC941766D, AT_CmdFunc_CNMI, SA_CMDCLS_SMS, 1, AT_CNMI_PERM},
    {"+CMGR", 0xBB8DE952, AT_CmdFunc_CMGR, SA_CMDCLS_SMS, 1, AT_CMGR_PERM},
    {"+CMGS", 0xCC8AD9C4, AT_CmdFunc_CMGS, SA_CMDCLS_SMS, 1, AT_CMGS_PERM},
    {"+CMGD", 0x4F595C03, AT_CmdFunc_CMGD, SA_CMDCLS_SMS, 1, AT_CMGD_PERM},
    
    {"+QICSGP", 0xF1EFBC7E, AT_CmdFunc_QICSGP, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QIACT", 0xF9CCCB46, AT_CmdFunc_QIACT, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QIDEACT", 0xAB782094, AT_CmdFunc_QIDEACT,  SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QIOPEN", 0x7146E27E, AT_CmdFunc_QIOPEN, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QICLOSE", 0x4EBCACA7, AT_CmdFunc_QICLOSE,  SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QISEND", 0x72455B17, AT_CmdFunc_QISEND, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QISENDEX", 0x505D0ED6, AT_CmdFunc_QISENDEX, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QIRD", 0x85F58DDF, AT_CmdFunc_QIRD, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QISTATE", 0xFE2EFF98, AT_CmdFunc_QISTATE,  SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QIDNSGIP", 0x3B05FBC1, AT_CmdFunc_QIDNSGIP, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    
    {"D", 0xA3B36A04, atCmdHandleD, SA_CMDCLS_CC, 1, AT_ATD_PERM},
    {"A", 0xD3D99E8B, atCmdHandleA, SA_CMDCLS_CC, 1, AT_ATA_PERM},
    {"H", 0xAA05262F, atCmdHandleH, SA_CMDCLS_CC, 1, AT_ATH_PERM},
    {"S0", 0xF6962CC4, atCmdHandleS0,  SA_CMDCLS_CC, 1, AT_AT_PERM},
    
    //FTM at commond
#ifdef KING_SDK_FTM_SUPPORT
    {"+CZPENTER", 0x42928613, AT_CmdFunc_CzpEnter, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPTEST", 0xEE756673, AT_CmdFunc_CzpTest,  SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPIMEI", 0x3D8B6187, AT_CmdFunc_CzpImei,  SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPCSN", 0x129A438B, AT_CmdFunc_CzpCsn, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPMEID", 0x6EFE94D9, AT_CmdFunc_CzpMeid,  SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPIPR", 0x2021C9D1, AT_CmdFunc_CzpIpr, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPAUTOON", 0xB9C05D0D, AT_CmdFunc_CzpAutoOn, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPCODE", 0x411F28E7, AT_CmdFunc_CzpCode,  SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPWMAC", 0x09F46D31, AT_CmdFunc_CzpWmac,  SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPNVBAK", 0xB8437A74, AT_CmdFunc_CzpNvback, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPAUDTEST", 0xD50F6856, AT_CmdFunc_CzpAudTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPCHGTEST", 0xBA7812EA, AT_CmdFunc_CzpChgTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPLDOTEST", 0x0B82E9B9, AT_CmdFunc_CzpLdoTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPSDTEST", 0xBCDC615E, AT_CmdFunc_CzpSdTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPUARTTEST", 0x3D799EBC, AT_CmdFunc_CzpUartTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPKEYTEST", 0xEAD966B0, AT_CmdFunc_CzpKeyTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
    {"+CZPGPIOTEST", 0xBC6F6B5B, AT_CmdFunc_CzpGpioTest, SA_CMDCLS_ENG, 1, AT_ENG_PERM},
#endif
    
    //MQTT at command
    {"+IMQTTMODE", 0xCBAB46DB, AT_CmdFunc_IMQTTMODE, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTOPEN", 0xF81182D4, AT_CmdFunc_IMQTTOPEN, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTAUTH", 0xA4BFB129, AT_CmdFunc_IMQTTAUTH, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTPARA", 0x78B3955D, AT_CmdFunc_IMQTTPARA, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTCONN", 0x464900EA, AT_CmdFunc_IMQTTCONN, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTDISCONN", 0xA988E78A, AT_CmdFunc_IMQTTDISCONN,  SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTSUB", 0x8A69F647, AT_CmdFunc_IMQTTSUB, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTUNSUB", 0xE09D73A9, AT_CmdFunc_IMQTTUNSUB, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTPUB", 0x882F481E, AT_CmdFunc_IMQTTPUB, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTSTATE", 0xC8A4E20E, AT_CmdFunc_IMQTTSTATE, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTRCVPUB", 0x34390B48, AT_CmdFunc_IMQTTRCVPUB, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTRCVCFG", 0x3BDCA37C, AT_CmdFunc_IMQTTRCVCFG, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTPUBIN", 0x5D40F476, AT_CmdFunc_IMQTTPUBIN, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+IMQTTRCVPUBIN", 0x5E74A298, AT_CmdFunc_IMQTTRCVPUBIN, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    
    //HTTP at command
    {"+QHTTPCFG", 0xA503E3F7, AT_CmdFunc_QHTTPCFG, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QHTTPURL", 0x04D432E8, AT_CmdFunc_QHTTPURL, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QHTTPGET", 0x0D995936, AT_CmdFunc_QHTTPGET, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    {"+QHTTPREAD", 0x3C76277D, AT_CmdFunc_QHTTPREAD, SA_CMDCLS_TCPIP, 1, AT_TCPIP_PERM},
    
    {"+CWLSCAN", 0xEB37C28C, AT_CmdFunc_CWLSCAN, SA_CMDCLS_NW, 1, AT_AT_PERM},   //WIFI SCAN
    
    //Fota at command
    {"+CZUPCHK", 0x8944C489, AT_CmdFunc_CZUPCHK, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CZUPDL", 0xD0A94B2A, AT_CmdFunc_CZUPDL,  SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CZUPDATE", 0x1F05287A, AT_CmdFunc_CZUPDATE, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    
    {"+QURCCFG", 0xEFEABE7F, AT_CmdFunc_QURCCFG, SA_CMDCLS_GC, 1 , AT_AT_PERM},

    //BT at command    
    {"+CBTENABLE", 0xBD9009B0, AT_CmdFunc_CBTENABLE, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTNAME", 0x722C404F, AT_CmdFunc_CBTNAME, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTMAC", 0xC1B329FB, AT_CmdFunc_CBTMAC, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTIBEACON", 0x2E5EAC09, AT_CmdFunc_CBTIBEACON, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTADVCFG", 0xB45CDFB0, AT_CmdFunc_CBTADVCFG, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTADVEN", 0x008AD829, AT_CmdFunc_CBTADVEN, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTBCONCFG", 0x5DC8204C, AT_CmdFunc_CBTBCONCFG, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLESEND", 0xCA00BCC5, AT_CmdFunc_CBLESEND, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLEDISCONN", 0x7411A197, AT_CmdFunc_CBLEDISCONN, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLESCAN", 0xA9C035A6, AT_CmdFunc_CBLESCAN, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLECONN", 0x775B8792, AT_CmdFunc_CBLECONN, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLEUUID", 0xBC0CD6AE, AT_CmdFunc_CBLEUUID, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBLEMTU", 0x7A105B15, AT_CmdFunc_CBLEMTU, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+CBTADVDATA", 0xE17B1E76, AT_CmdFunc_CBTADVDATA, SA_CMDCLS_NW, 1 , AT_AT_PERM},

    //GNSS at command
    {"+QGPS", 0x3E8E4790, AT_CmdFunc_QGPS, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+QGPSEND", 0xDE70BE10, AT_CmdFunc_QGPSEND, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"+QGPSLOC", 0x56DE217D, AT_CmdFunc_QGPSLOC, SA_CMDCLS_NW, 1 , AT_AT_PERM},

    //scan code command
    {"+CZSCANCODE", 0xB1826824, AT_CmdFunc_CZSCANCODE, SA_CMDCLS_HW, 1 , AT_AT_PERM},
    {"+CZCAMPARAM", 0x3FEF2561, AT_CmdFunc_CZCAMPARAM, SA_CMDCLS_HW, 1 , AT_AT_PERM},

    // dual sim command
    {"^DSS", 0x1EF18C48, AT_CmdFunc_DSS, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    {"^DSSWITCH", 0xCDA09C4A, AT_CmdFunc_SIMSWITCH, SA_CMDCLS_NW, 1 , AT_AT_PERM},
    
    // lcd command
    {"+CZLCDONOFF", 0x20E11845, AT_CmdFunc_CZLCDONOFF, SA_CMDCLS_HW, 1 , AT_AT_PERM},
    {"+CZLCDBRIGHTNESS", 0xB8DD9F00, AT_CmdFunc_CZLCDBRIGHTNESS, SA_CMDCLS_HW, 1 , AT_AT_PERM},

    {"+CZCRMODE", 0x8D1EEA4D, AT_CmdFunc_Czcrmode, SA_CMDCLS_HW, 1 , AT_AT_PERM},

    {"+CZEM2SD", 0x276D0825, AT_CmdFunc_CZEM2SD, SA_CMDCLS_SYS, 1, AT_AT_PERM},
    {"+SET7SRESET", 0x5F455425, AT_CmdFunc_SET7SRESET, SA_CMDCLS_SYS, 1, AT_AT_PERM},
};

int atSearch(uint8_t* pName, unsigned len)
{
    uint32_t crc32;
    uint32_t tableLen = sizeof(g_AtCommandTable)/sizeof(g_AtCommandTable[0]);
    for(uint32_t i=0;i<len;i++)
    {
        if(pName[i]>='a' && pName[i]<='z')
        {
            pName[i] = pName[i]-32;
        }
    }
    crc32 = crc32Calc(pName, len);
    
    for(uint32_t i=0;i<tableLen;i++)
    {
        if(crc32 == g_AtCommandTable[i].crc32)
            return i;
    }
    return -1;
}

const SA_COMMAND_TABLE_T *at_GetCmdDescriptor(uint8_t *name, unsigned len)
{
    ATCMDLOGS(D, TSM(0), "AT CMD search %s (%d)", name, len);
    int index = atSearch(name,len);
    if(index != -1)
    {
        int cmp = AT_StrCaselessCmp(name, g_AtCommandTable[index].pName);
        ATCMDLOG(D, "AT CMD found index=%d cmp=%d", index, cmp);
        return (cmp == 0)? &g_AtCommandTable[index] : NULL;
    }
    return NULL;
}
