/******************************************************************************
** File Name:      version_cheerzing.h                                       *
** Author:         steven.chen                                               *
** DATE:           07/27/2015                                                *
** Copyright:      2015 Xiamen Cheerzing IOT Technology Co., Ltd.            *
**                 All Rights Reserved.                                      *
** Description:    This is generated by build script.                        *
******************************************************************************/
/*
 * 禁止改变以下宏名及宏定义顺序！！！
 * 客户可以修改宏体：
 * CZ_VENDOR：厂商名称，字符串长度最大15
 * CZ_PRODUCT_MODEL： 型号，字符串长度最大15
 * CZ_SW_MAJOR：主版本号，最大255
 * CZ_SW_MINOR: 次版本号，最大255
 * CZ_SW_BUILDNUMBER: 编译版本号，最大65535
 *
 */
#ifndef __VERSION_CHEERZING_H__
#define __VERSION_CHEERZING_H__
#define CZ_VENDOR   "CHEERZING"
#define CZ_PRODUCT_MODEL "ModemApp"
#define CZ_PROJECT_NAME "ModemApp"
#define CZ_SW_MAJOR 1
#define CZ_SW_MINOR 0
#define CZ_SW_BUILDNUMBER 14
#define CZ_SVN_REV 633
#define CZ_BUILD_YEAR 20
#define CZ_BUILD_MONTH 7
#define CZ_BUILD_DAY 27
#define CZ_BUILD_HOUR 9
#define CZ_HW_MAJOR 1
#define CZ_HW_MINOR 0
#define CZ_BUILD_FLAG "R"
#endif //__VERSION_CHEERZING_H__

