/******************************************************************************
** File Name:      version_cheerzing.h                                       *
** Author:         steven.chen                                               *
** DATE:           07/27/2015                                                *
** Copyright:      2015 Xiamen Cheerzing IOT Technology Co., Ltd.            *
**                 All Rights Reserved.                                      *
** Description:    This is generated by build script.                        *
******************************************************************************/
#ifndef __VERSION_CHEERZING_H__
#define __VERSION_CHEERZING_H__
#define CZ_VENDOR "CHEERZING"
#define CZ_PRODUCT_MODEL "KingSDK"
#define CZ_PROJECT_NAME "UIS8910DM"
#define CZ_SW_MAJOR 1
#define CZ_SW_MINOR 0
#define CZ_SW_BUILDNUMBER 131
#define CZ_SVN_REV 1426
#define CZ_BUILD_YEAR 21
#define CZ_BUILD_MONTH 10
#define CZ_BUILD_DAY 12
#define CZ_BUILD_HOUR 10
#define CZ_HW_MAJOR 1
#define CZ_HW_MINOR 0
#define CZ_BUILD_FLAG "R"
#endif //__VERSION_CHEERZING_H__
